# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DetailViewTabBarUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DetailViewTabBar(object):
    def setupUi(self, DetailViewTabBar):
        DetailViewTabBar.setObjectName("DetailViewTabBar")
        DetailViewTabBar.resize(744, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DetailViewTabBar.sizePolicy().hasHeightForWidth())
        DetailViewTabBar.setSizePolicy(sizePolicy)
        DetailViewTabBar.setMaximumSize(QtCore.QSize(16999, 16999))
        self.verticalLayout = QtWidgets.QVBoxLayout(DetailViewTabBar)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_export = QtWidgets.QPushButton(DetailViewTabBar)
        self.pushButton_export.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_export.setFont(font)
        self.pushButton_export.setObjectName("pushButton_export")
        self.horizontalLayout.addWidget(self.pushButton_export)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(DetailViewTabBar)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(DetailViewTabBar)
        QtCore.QMetaObject.connectSlotsByName(DetailViewTabBar)

    def retranslateUi(self, DetailViewTabBar):
        _translate = QtCore.QCoreApplication.translate
        DetailViewTabBar.setWindowTitle(_translate("DetailViewTabBar", "Form"))
        self.pushButton_export.setText(_translate("DetailViewTabBar", "导出.."))
