# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projectTabBarUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_projectTabBar(object):
    def setupUi(self, projectTabBar):
        projectTabBar.setObjectName("projectTabBar")
        projectTabBar.resize(1652, 658)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(projectTabBar.sizePolicy().hasHeightForWidth())
        projectTabBar.setSizePolicy(sizePolicy)
        projectTabBar.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(projectTabBar)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(projectTabBar)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setWordWrap(True)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4, 0, QtCore.Qt.AlignTop)
        self.groupBox_6 = QtWidgets.QGroupBox(projectTabBar)
        self.groupBox_6.setMinimumSize(QtCore.QSize(60, 120))
        self.groupBox_6.setMaximumSize(QtCore.QSize(12000, 24000))
        self.groupBox_6.setBaseSize(QtCore.QSize(120, 240))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_6.setStyleSheet("background-color :rgb(235, 235, 200)")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout.setContentsMargins(5, 20, 5, 2)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setMinimumSize(QtCore.QSize(80, 100))
        self.groupBox_7.setMaximumSize(QtCore.QSize(110, 130))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_13.setContentsMargins(2, 8, 2, 2)
        self.verticalLayout_13.setSpacing(1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_13.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_13.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_13.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_13.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_13.addWidget(self.radioButton_5)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox_status = QtWidgets.QGroupBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_status.setFont(font)
        self.groupBox_status.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_status.setObjectName("groupBox_status")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_status)
        self.verticalLayout_16.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout.addWidget(self.groupBox_status)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        spacerItem = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalGroupBox = QtWidgets.QGroupBox(projectTabBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox.setSizePolicy(sizePolicy)
        self.verticalGroupBox.setMinimumSize(QtCore.QSize(60, 150))
        self.verticalGroupBox.setMaximumSize(QtCore.QSize(12000, 28000))
        self.verticalGroupBox.setBaseSize(QtCore.QSize(120, 280))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.verticalGroupBox.setFont(font)
        self.verticalGroupBox.setAutoFillBackground(False)
        self.verticalGroupBox.setStyleSheet("background-color :rgb(220, 235, 235)")
        self.verticalGroupBox.setCheckable(False)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setContentsMargins(5, 13, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3.addWidget(self.verticalGroupBox)
        self.verticalLayout_3.setStretch(2, 1)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(projectTabBar)
        self.label.setStyleSheet("font:bold ; font-family: Microsoft Yahei")
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(projectTabBar)
        self.tableWidget.setStyleSheet("background-color :rgb(235, 235, 200)")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget.setLineWidth(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(projectTabBar)
        self.label_2.setStyleSheet("font:bold ; font-family: Microsoft Yahei")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.tableWidget_2 = QtWidgets.QTableWidget(projectTabBar)
        self.tableWidget_2.setStyleSheet("background-color :rgb(220, 235, 235)")
        self.tableWidget_2.setLineWidth(1)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_8.addWidget(self.tableWidget_2)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(projectTabBar)
        self.label_3.setStyleSheet("font:bold ; font-family: Microsoft Yahei")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.tableWidget_3 = QtWidgets.QTableWidget(projectTabBar)
        self.tableWidget_3.setAutoFillBackground(False)
        self.tableWidget_3.setStyleSheet("background-color :rgb(220, 235, 235)")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.verticalLayout_9.addWidget(self.tableWidget_3)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 3)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.line_4 = QtWidgets.QFrame(projectTabBar)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_5 = QtWidgets.QFrame(projectTabBar)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_2.addWidget(self.line_5)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_files = QtWidgets.QPushButton(projectTabBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_files.sizePolicy().hasHeightForWidth())
        self.pushButton_files.setSizePolicy(sizePolicy)
        self.pushButton_files.setObjectName("pushButton_files")
        self.gridLayout_4.addWidget(self.pushButton_files, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(projectTabBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(projectTabBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(projectTabBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_4)
        self.groupBox_deal = QtWidgets.QGroupBox(projectTabBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_deal.sizePolicy().hasHeightForWidth())
        self.groupBox_deal.setSizePolicy(sizePolicy)
        self.groupBox_deal.setMaximumSize(QtCore.QSize(16777215, 380))
        self.groupBox_deal.setSizeIncrement(QtCore.QSize(1, 1))
        self.groupBox_deal.setBaseSize(QtCore.QSize(0, 38))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_deal.setFont(font)
        self.groupBox_deal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.groupBox_deal.setStyleSheet("border-radius:10;border-width:1;border-style:solid;border-color:rgb(210,210,220)")
        self.groupBox_deal.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_deal.setObjectName("groupBox_deal")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_deal)
        self.verticalLayout_15.setContentsMargins(-1, 13, -1, -1)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_2.addWidget(self.groupBox_deal)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.line_8 = QtWidgets.QFrame(projectTabBar)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_2.addWidget(self.line_8)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 2)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(projectTabBar)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_investigation = QtWidgets.QLabel(projectTabBar)
        self.label_investigation.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_investigation.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_investigation.setObjectName("label_investigation")
        self.horizontalLayout_3.addWidget(self.label_investigation)
        self.label_setup = QtWidgets.QLabel(projectTabBar)
        self.label_setup.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_setup.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_setup.setObjectName("label_setup")
        self.horizontalLayout_3.addWidget(self.label_setup)
        self.label_lab = QtWidgets.QLabel(projectTabBar)
        self.label_lab.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_lab.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_lab.setObjectName("label_lab")
        self.horizontalLayout_3.addWidget(self.label_lab)
        self.label_scaleup = QtWidgets.QLabel(projectTabBar)
        self.label_scaleup.setMaximumSize(QtCore.QSize(16777215, 26))
        self.label_scaleup.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_scaleup.setObjectName("label_scaleup")
        self.horizontalLayout_3.addWidget(self.label_scaleup)
        self.label_clinic = QtWidgets.QLabel(projectTabBar)
        self.label_clinic.setMaximumSize(QtCore.QSize(16777215, 26))
        self.label_clinic.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_clinic.setObjectName("label_clinic")
        self.horizontalLayout_3.addWidget(self.label_clinic)
        self.label_filing = QtWidgets.QLabel(projectTabBar)
        self.label_filing.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_filing.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_filing.setObjectName("label_filing")
        self.horizontalLayout_3.addWidget(self.label_filing)
        self.label_commercial = QtWidgets.QLabel(projectTabBar)
        self.label_commercial.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_commercial.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_commercial.setObjectName("label_commercial")
        self.horizontalLayout_3.addWidget(self.label_commercial)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.horizontalLayout_3.setStretch(4, 1)
        self.horizontalLayout_3.setStretch(5, 1)
        self.horizontalLayout_3.setStretch(6, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.hSlider_progress = QtWidgets.QSlider(projectTabBar)
        self.hSlider_progress.setMaximumSize(QtCore.QSize(4000, 16777215))
        self.hSlider_progress.setSizeIncrement(QtCore.QSize(0, 0))
        self.hSlider_progress.setBaseSize(QtCore.QSize(400, 0))
        self.hSlider_progress.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.hSlider_progress.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.hSlider_progress.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hSlider_progress.setMaximum(6)
        self.hSlider_progress.setPageStep(1)
        self.hSlider_progress.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_progress.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.hSlider_progress.setObjectName("hSlider_progress")
        self.horizontalLayout_5.addWidget(self.hSlider_progress)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 15)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.line = QtWidgets.QFrame(projectTabBar)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_chance = QtWidgets.QLabel(projectTabBar)
        self.label_chance.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_chance.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_chance.setObjectName("label_chance")
        self.verticalLayout_11.addWidget(self.label_chance)
        self.comboBox_chance = QtWidgets.QComboBox(projectTabBar)
        self.comboBox_chance.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_chance.setObjectName("comboBox_chance")
        self.verticalLayout_11.addWidget(self.comboBox_chance)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.line_2 = QtWidgets.QFrame(projectTabBar)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_pricing1 = QtWidgets.QLabel(projectTabBar)
        self.label_pricing1.setObjectName("label_pricing1")
        self.horizontalLayout_11.addWidget(self.label_pricing1)
        self.lineEdit_pricing1 = QtWidgets.QLineEdit(projectTabBar)
        self.lineEdit_pricing1.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_pricing1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_pricing1.setObjectName("lineEdit_pricing1")
        self.horizontalLayout_11.addWidget(self.lineEdit_pricing1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_pricing2 = QtWidgets.QLabel(projectTabBar)
        self.label_pricing2.setObjectName("label_pricing2")
        self.horizontalLayout_9.addWidget(self.label_pricing2)
        self.lineEdit_pricing2 = QtWidgets.QLineEdit(projectTabBar)
        self.lineEdit_pricing2.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_pricing2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_pricing2.setObjectName("lineEdit_pricing2")
        self.horizontalLayout_9.addWidget(self.lineEdit_pricing2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_14)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_scale1 = QtWidgets.QLabel(projectTabBar)
        self.label_scale1.setObjectName("label_scale1")
        self.horizontalLayout_4.addWidget(self.label_scale1)
        self.lineEdit_pricing3 = QtWidgets.QLineEdit(projectTabBar)
        self.lineEdit_pricing3.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_pricing3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_pricing3.setObjectName("lineEdit_pricing3")
        self.horizontalLayout_4.addWidget(self.lineEdit_pricing3)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_rival_disk = QtWidgets.QPushButton(projectTabBar)
        self.pushButton_rival_disk.setMaximumSize(QtCore.QSize(80, 25))
        self.pushButton_rival_disk.setObjectName("pushButton_rival_disk")
        self.horizontalLayout_6.addWidget(self.pushButton_rival_disk)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_ladderpricing = QtWidgets.QPushButton(projectTabBar)
        self.pushButton_ladderpricing.setMaximumSize(QtCore.QSize(80, 25))
        self.pushButton_ladderpricing.setObjectName("pushButton_ladderpricing")
        self.verticalLayout_6.addWidget(self.pushButton_ladderpricing)
        self.pushButton_demand = QtWidgets.QPushButton(projectTabBar)
        self.pushButton_demand.setMaximumSize(QtCore.QSize(84, 25))
        self.pushButton_demand.setObjectName("pushButton_demand")
        self.verticalLayout_6.addWidget(self.pushButton_demand)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.line_3 = QtWidgets.QFrame(projectTabBar)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_incharge = QtWidgets.QLabel(projectTabBar)
        self.label_incharge.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_incharge.setObjectName("label_incharge")
        self.horizontalLayout_8.addWidget(self.label_incharge)
        self.pushButton_new = QtWidgets.QPushButton(projectTabBar)
        self.pushButton_new.setMaximumSize(QtCore.QSize(30, 20))
        self.pushButton_new.setObjectName("pushButton_new")
        self.horizontalLayout_8.addWidget(self.pushButton_new)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.comboBox_personnel = QtWidgets.QComboBox(projectTabBar)
        self.comboBox_personnel.setObjectName("comboBox_personnel")
        self.verticalLayout_12.addWidget(self.comboBox_personnel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        self.line_6 = QtWidgets.QFrame(projectTabBar)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_2.addWidget(self.line_6)
        self.horizontalLayout_2.setStretch(3, 7)
        self.horizontalLayout_2.setStretch(5, 4)
        self.horizontalLayout_2.setStretch(11, 1)
        self.horizontalLayout_2.setStretch(13, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.line_7 = QtWidgets.QFrame(projectTabBar)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_5.addWidget(self.line_7)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(projectTabBar)
        QtCore.QMetaObject.connectSlotsByName(projectTabBar)

    def retranslateUi(self, projectTabBar):
        _translate = QtCore.QCoreApplication.translate
        projectTabBar.setWindowTitle(_translate("projectTabBar", "Form"))
        self.label_4.setText(_translate("projectTabBar", "nothing yet"))
        self.groupBox_6.setTitle(_translate("projectTabBar", "当前任务"))
        self.groupBox_7.setTitle(_translate("projectTabBar", "待办类型"))
        self.radioButton.setText(_translate("projectTabBar", "A上游信息"))
        self.radioButton_2.setText(_translate("projectTabBar", "B下游信息"))
        self.radioButton_3.setText(_translate("projectTabBar", "C内部决策"))
        self.radioButton_4.setText(_translate("projectTabBar", "D合同协议"))
        self.radioButton_5.setText(_translate("projectTabBar", "E资料文件"))
        self.groupBox_status.setTitle(_translate("projectTabBar", "待办状态"))
        self.verticalGroupBox.setTitle(_translate("projectTabBar", "项目情况"))
        self.label.setText(_translate("projectTabBar", "任务记录"))
        self.label_2.setText(_translate("projectTabBar", "会议记录"))
        self.label_3.setText(_translate("projectTabBar", "备注记录"))
        self.pushButton_files.setText(_translate("projectTabBar", "商务/文件︿"))
        self.pushButton_3.setText(_translate("projectTabBar", "项目推进︿"))
        self.pushButton.setText(_translate("projectTabBar", "新增记录"))
        self.pushButton_2.setText(_translate("projectTabBar", "插入记录"))
        self.groupBox_deal.setTitle(_translate("projectTabBar", "成交情况"))
        self.label_5.setText(_translate("projectTabBar", "管线进度"))
        self.label_investigation.setText(_translate("projectTabBar", "调研"))
        self.label_setup.setText(_translate("projectTabBar", "立项"))
        self.label_lab.setText(_translate("projectTabBar", "小试"))
        self.label_scaleup.setText(_translate("projectTabBar", "中试"))
        self.label_clinic.setText(_translate("projectTabBar", "临床"))
        self.label_filing.setText(_translate("projectTabBar", "申报"))
        self.label_commercial.setText(_translate("projectTabBar", "商业"))
        self.label_chance.setText(_translate("projectTabBar", "机会情况"))
        self.label_pricing1.setText(_translate("projectTabBar", "当前报价"))
        self.lineEdit_pricing1.setPlaceholderText(_translate("projectTabBar", "元"))
        self.label_pricing2.setText(_translate("projectTabBar", "对手报价"))
        self.lineEdit_pricing2.setPlaceholderText(_translate("projectTabBar", "元"))
        self.label_scale1.setText(_translate("projectTabBar", "成交价"))
        self.lineEdit_pricing3.setPlaceholderText(_translate("projectTabBar", "元"))
        self.pushButton_rival_disk.setText(_translate("projectTabBar", "对手盘︿"))
        self.pushButton_ladderpricing.setText(_translate("projectTabBar", "︿"))
        self.pushButton_demand.setText(_translate("projectTabBar", "︿"))
        self.label_incharge.setText(_translate("projectTabBar", "负责人:"))
        self.pushButton_new.setText(_translate("projectTabBar", "+.."))

